apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-go-xpltzifq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-go-xpltzifq 
  name: backend-tests-go-xpltzifq
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-go-xpltzifq 
